name: Post a comment
on:
  pull_request:
    types: opened
permissions:
  pull-requests: write
jobs:
  wekcome:
    name: Post welcome comment
    runs-on: ubuntu-20.04
    steps:
      - run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
    
